src/main/asciidoc/licenseDebugReport.json
src/main/asciidoc/solicitor_userguide.adoc

The Descritpion of how the Tool works with an Android project build on gradle was added

Added Gradle for Android

---

src/main/asciidoc/solicitor_userguide.adoc
src/main/java/com/devonfw/tools/solicitor/common/FileInputStreamFactory.java
src/main/java/com/devonfw/tools/solicitor/common/InputStreamFactory.java
src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
src/main/java/com/devonfw/tools/solicitor/common/UrlInputStreamFactory.java
src/main/java/com/devonfw/tools/solicitor/config/ConfigReader.java
src/main/java/com/devonfw/tools/solicitor/config/RuleConfig.java
src/main/java/com/devonfw/tools/solicitor/config/SolicitorConfig.java
src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/DroolsRuleEngine.java
src/main/resources/com/devonfw/tools/solicitor/config/solicitor_base.cfg
src/main/resources/samples/generic_maven_sample.cfg
src/main/resources/samples/solicitor_itself.cfg
src/main/resources/samples/solicitor_sample.cfg
src/main/resources/samples/solicitor_sample_filesystem.cfg
src/test/java/com/devonfw/tools/solicitor/config/SolicitorConfigTests.java

Optional rulegroups; Version info in config file

---

src/main/resources/com/devonfw/tools/solicitor/config/solicitor_base.cfg
src/main/resources/com/devonfw/tools/solicitor/sql/normalizedlicenses_aggregated_applications.sql

This implements enhancement #53 .

Implementation of inventory report with aggregated applications

---

pom.xml
src/main/java/com/devonfw/tools/solicitor/SolicitorSetup.java
src/main/java/com/devonfw/tools/solicitor/SolicitorVersion.java
src/main/java/com/devonfw/tools/solicitor/common/ResourceToFileCopier.java
src/main/java/com/devonfw/tools/solicitor/common/webcontent/CachingWebContentProviderBase.java
src/main/java/com/devonfw/tools/solicitor/common/webcontent/ClasspathWebContentProvider.java
src/main/java/com/devonfw/tools/solicitor/config/ApplicationConfig.java
src/main/java/com/devonfw/tools/solicitor/config/ReaderConfig.java
src/main/java/com/devonfw/tools/solicitor/config/RuleConfig.java
src/main/java/com/devonfw/tools/solicitor/config/SolicitorConfig.java
src/main/java/com/devonfw/tools/solicitor/config/WriterConfig.java
src/main/java/com/devonfw/tools/solicitor/model/ModelRoot.java
src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/ApplicationComponentImpl.java
src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/NormalizedLicenseImpl.java
src/main/java/com/devonfw/tools/solicitor/model/impl/masterdata/EngagementImpl.java
src/main/java/com/devonfw/tools/solicitor/model/inventory/ApplicationComponent.java
src/main/java/com/devonfw/tools/solicitor/model/inventory/NormalizedLicense.java
src/main/java/com/devonfw/tools/solicitor/model/inventory/RawLicense.java
src/main/java/com/devonfw/tools/solicitor/model/masterdata/Application.java
src/main/java/com/devonfw/tools/solicitor/model/masterdata/Engagement.java
src/main/java/com/devonfw/tools/solicitor/reader/AbstractReader.java
src/main/java/com/devonfw/tools/solicitor/reader/gradle/model/Dependency.java
src/main/java/com/devonfw/tools/solicitor/reader/gradle/model/License.java
src/main/java/com/devonfw/tools/solicitor/reader/gradle/model/LicenseSummary.java
src/main/java/com/devonfw/tools/solicitor/reader/maven/model/Dependency.java
src/main/java/com/devonfw/tools/solicitor/reader/maven/model/License.java
src/main/java/com/devonfw/tools/solicitor/reader/maven/model/LicenseSummary.java
src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/DroolsRuleEngine.java
src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/ModelHelper.java

Changes required for supporting java 11.

changes for supporting java 11 and some fix

---

documentation/master-solicitor.asciidoc

devonfw is a trademark, which needs to be written in lower case only

Correct typography

---

.github/workflows/spellcheck.yml
documentation/master-solicitor.asciidoc
solicitor.dict
src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
src/main/java/com/devonfw/tools/solicitor/common/content/web/DirectUrlWebContentProvider.java

INFO instead of WARN message if downloading content fails. This closes #86

---

documentation/master-solicitor.asciidoc

Fix Broken Links by removing / and updating the references

Fix Broken Links

---

core/src/main/java/com/devonfw/tools/solicitor/common/ResourceToFileCopier.java
core/src/main/resources/application.properties
core/src/main/resources/samples/application-extension.properties
documentation/files/application-extension.properties
documentation/master-solicitor.asciidoc

Allow an additional user guide to be extracted when using an extension.

---

core/src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
core/src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/DroolsDecisionTableReader.java
core/src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/DroolsRuleEngine.java
core/src/main/resources/com/devonfw/tools/solicitor/config/solicitor_base.cfg
documentation/master-solicitor.asciidoc

This resolves #15 with updated documentation.

Enable Decision Table data to be provided as CSV

---

core/src/main/java/com/devonfw/tools/solicitor/scancode/ScancodeFileAdapter.java
documentation/master-solicitor.asciidoc

This feature adds support for the new API changes of the new scancode release (v31) https://github.com/nexB/scancode-toolkit/releases/tag/v31.0.1.

Scancode Release v31 Integration

---

core/src/main/resources/com/devonfw/tools/solicitor/templates/ScancodeScanScript.vm
core/src/main/resources/com/devonfw/tools/solicitor/templates/ScancodeScript.vm
documentation/master-solicitor.asciidoc

Avoid failure of report generation if PackageURL is not set.

---

core/src/main/java/com/devonfw/tools/solicitor/writer/velocity/VelocityWriter.java
documentation/master-solicitor.asciidoc

Reset velocity engine on initialization of each template

---

core/pom.xml
documentation/master-solicitor.asciidoc

Fix dependency declaration of solicitor-documentation.pdf artifact

---

core/pom.xml
core/src/test/resources/licenses/http___raw_githubusercontent_com_auth0_java_jwt_master_LICENSE
documentation/master-solicitor.asciidoc

Add com.auth0/java-jwt as dependency (#158).

---

core/src/main/java/com/devonfw/tools/solicitor/model/ModelImporterExporter.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/AbstractModelObject.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/ModelFactoryImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/ModelRootImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/TextPool.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/TextPoolImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/NormalizedLicenseImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/inventory/NormalizedLicense.java
core/src/test/java/com/devonfw/tools/solicitor/model/impl/TextPoolImplTest.java
documentation/master-solicitor.asciidoc

Include license texts in persisted datamodel json file

---

core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfoInventoryProcessor.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/LicenseInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeFileAdapter.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/TextPool.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/TextPoolImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/ApplicationComponentImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/NormalizedLicenseImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/RawLicenseImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/inventory/ApplicationComponent.java
core/src/main/java/com/devonfw/tools/solicitor/model/inventory/RawLicense.java
documentation/master-solicitor.asciidoc

Include notice file content and license texts in ComponentInfo interface

---

app/pom.xml
core/pom.xml
core/src/main/java/com/devonfw/tools/solicitor/model/impl/TextPool.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/TextPoolImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/NormalizedLicenseImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/RawLicenseImpl.java
core/src/test/java/com/devonfw/tools/solicitor/model/impl/TextPoolImplTest.java
documentation/master-solicitor.asciidoc
documentation/pom.xml
logo/pom.xml
pom.xml

Changed handling of null values in TextPool

---

core/src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
core/src/main/java/com/devonfw/tools/solicitor/common/content/web/DirectUrlWebContentProvider.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfoInventoryProcessor.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeFileAdapter.java
core/src/main/resources/application.properties
documentation/files/application.properties
documentation/master-solicitor.asciidoc

This implements and closes #171 .

Improvements of mapping ScanCode data to Solicitor data model

---

core/src/main/java/com/devonfw/tools/solicitor/InventoryProcessor.java
core/src/main/java/com/devonfw/tools/solicitor/common/packageurl/PackageURLHandler.java
core/src/main/java/com/devonfw/tools/solicitor/common/packageurl/impl/AbstractSingleKindPackageURLHandler.java
core/src/main/java/com/devonfw/tools/solicitor/common/packageurl/impl/DelegatingPackageURLHandlerImpl.java
core/src/main/java/com/devonfw/tools/solicitor/common/packageurl/impl/MavenPackageURLHandlerImpl.java
core/src/main/java/com/devonfw/tools/solicitor/common/packageurl/impl/NpmPackageURLHandlerImpl.java
core/src/main/java/com/devonfw/tools/solicitor/common/packageurl/impl/PyPIPackageURLHandlerImpl.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfoInventoryProcessor.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeFileAdapter.java
core/src/main/java/com/devonfw/tools/solicitor/model/DefaultDownloadUrlInventoryProcessor.java
core/src/main/java/com/devonfw/tools/solicitor/model/impl/inventory/ApplicationComponentImpl.java
core/src/main/java/com/devonfw/tools/solicitor/model/inventory/ApplicationComponent.java
core/src/main/resources/com/devonfw/tools/solicitor/templates/ScancodeScript.vm
documentation/master-solicitor.asciidoc

Add download URLs for binaries and sources to ApplicationComponent

---

core/src/main/java/com/devonfw/tools/solicitor/common/content/FilesystemCachingContentProvider.java
documentation/master-solicitor.asciidoc

Do not cache local files

---

core/src/main/resources/com/devonfw/tools/solicitor/sql/allden_normalizedlicenses.sql
documentation/master-solicitor.asciidoc

This fixes https://github.com/devonfw/solicitor/issues/185

Simple report order fix

---

core/pom.xml
core/src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
core/src/main/java/com/devonfw/tools/solicitor/reader/cyclonedx/CyclonedxReader.java
core/src/test/java/com/devonfw/tools/solicitor/reader/cyclonedx/CyclonedxReaderTests.java
core/src/test/resources/mavensbom.json
core/src/test/resources/npmsbom.json
documentation/master-solicitor.asciidoc
solicitor.dict

- Implemented a CycloneDX Reader, to enable reading SBOMs in CycloneDX 1.4 or 1.5 format.
- Added Unit Tests
- Added Documentation for CDXGEN, a tool to create SBOMs in CycloneDX format

CycloneDX Reader

---

core/src/main/java/com/devonfw/tools/solicitor/Solicitor.java
core/src/main/java/com/devonfw/tools/solicitor/lifecycle/AbstractSolicitorLifecycleListener.java
core/src/main/java/com/devonfw/tools/solicitor/lifecycle/LifecycleListenerHolder.java
core/src/main/java/com/devonfw/tools/solicitor/lifecycle/SolicitorLifecycleListener.java
documentation/master-solicitor.asciidoc

See: https://github.com/devonfw/solicitor/issues/208

Additional method in SolicitorLifecycleListener

---

core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfoData.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfoInventoryProcessor.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/ComponentInfoProvider.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/DataStatusValue.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/DefaultComponentInfoDataImpl.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/DefaultComponentInfoImpl.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/curation/ComponentInfoCuratorImpl.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/curation/CuratingComponentInfoAdapter.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/FileScancodeRawComponentInfoProvider.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/FilteredScancodeComponentInfoProvider.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeComponentInfo.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeProcessingFailedException.java
core/src/main/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeRawComponentInfoProvider.java
core/src/test/java/com/devonfw/tools/solicitor/componentinfo/scancode/FilteredScancodeComponentInfoProviderTests.java
core/src/test/java/com/devonfw/tools/solicitor/componentinfo/scancode/ScancodeComponentInfoAdapterTest.java
documentation/master-solicitor.asciidoc

Make use of data status

---

core/src/main/java/com/devonfw/tools/solicitor/SolicitorCliProcessor.java
core/src/test/java/com/devonfw/tools/solicitor/SolicitorCliProcessorTest.java
documentation/master-solicitor.asciidoc

Fix for #223 (broken command line parsing)

---

core/src/main/resources/com/devonfw/tools/solicitor/sql/normalizedlicenses_aggregated_applications.sql
documentation/master-solicitor.asciidoc

The _dataStatus_ field of the _aggregated OSS-Inventory_ was not filled. Added _dataStatus_ to the SQL select statement to fix this bug.

Bugfix data status aggregated inventory

---

core/src/main/java/com/devonfw/tools/solicitor/Solicitor.java
core/src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
documentation/master-solicitor.asciidoc

Java 8 deprecation Stage 1

---

core/pom.xml
core/src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/DroolsRuleEngine.java
documentation/master-solicitor.asciidoc

Downgrade drools to 8.27.0.Beta to ensure Java 8 compatibility

---

documentation/master-solicitor.asciidoc
solicitor.dict

Improving usage pattern documentation

---

core/src/main/java/com/devonfw/tools/solicitor/config/ConfigFactory.java
core/src/main/java/com/devonfw/tools/solicitor/reader/npmlicensecrawler/NpmLicenseCrawlerReader.java
core/src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/ModelHelper.java
core/src/main/resources/com/devonfw/tools/solicitor/config/solicitor_base.cfg
core/src/test/resources/ownlicenseinfo/solicitor_own.cfg
documentation/master-solicitor.asciidoc

This PR solves https://github.com/devonfw/solicitor/issues/263

Deprecate features stage2

---

core/src/main/resources/com/devonfw/tools/solicitor/sql/normalizedlicenses_aggregated_applications.sql
documentation/master-solicitor.asciidoc

Remove applicationName from correlation keys as this not a stable key in case of the performed aggregation

Improve correlation of records (delta processing) for aggregated reports

---

core/src/main/java/com/devonfw/tools/solicitor/reader/yarn/YarnReader.java
documentation/master-solicitor.asciidoc

This closes https://github.com/devonfw/solicitor/issues/303 .

Fix license counter in YarnReader

---

core/src/main/java/com/devonfw/tools/solicitor/common/LogMessages.java
core/src/main/java/com/devonfw/tools/solicitor/reader/AbstractReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/csv/CsvReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/cyclonedx/CyclonedxReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/gradle/GradleLicenseReportReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/gradle/GradleReader2.java
core/src/main/java/com/devonfw/tools/solicitor/reader/maven/MavenReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/npmlicensechecker/NpmLicenseCheckerReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/npmlicensecrawler/NpmLicenseCrawlerReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/ort/OrtReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/piplicenses/PipLicensesReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/yarn/YarnReader.java
core/src/main/java/com/devonfw/tools/solicitor/reader/yarnmodern/YarnModernReader.java
core/src/test/java/com/devonfw/tools/solicitor/reader/AbstractReaderTest.java
core/src/test/java/com/devonfw/tools/solicitor/reader/csv/CsvReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/cyclonedx/CyclonedxReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/gradle/GradleLicenseReportReaderTest.java
core/src/test/java/com/devonfw/tools/solicitor/reader/gradle/GradleReader2Tests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/maven/MavenReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/npmlicensechecker/NpmLicenseCheckerReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/npmlicensecrawler/NpmLicenseCrawlerReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/ort/OrtReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/piplicenses/PipReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/yarn/YarnReaderTests.java
core/src/test/java/com/devonfw/tools/solicitor/reader/yarnmodern/YarnModernReaderTests.java
documentation/master-solicitor.asciidoc

Reader Filter

---

core/pom.xml
core/src/main/java/com/devonfw/tools/solicitor/common/LicenseTextHelper.java
core/src/main/java/com/devonfw/tools/solicitor/ruleengine/drools/DroolsRuleEngine.java
documentation/master-solicitor.asciidoc

Upgrade drools to most recent version 8 and perform other version updates for compatibility with JDK 21
